import { spawn } from 'node:child_process'
import { existsSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { fileURLToPath } from 'node:url'
import type { GameAtomExecutor, SkillProgram, SkillRecord, SkillRunResult, SkillStepTrace, SkillValue } from './contracts.js'

/** Fault isolation for our restricted interpreter, NOT an OS sandbox for arbitrary JS. */
export function runSkillProcess(skillId: string, skillVersion: number, program: SkillProgram,
  atoms: ReadonlySet<string>, executor: GameAtomExecutor, signal: AbortSignal,
  dependencies: ReadonlyMap<string, SkillRecord>, params: Record<string, SkillValue> = {}): Promise<SkillRunResult> {
  const observed: SkillStepTrace[] = []
  const failure = (error: string): SkillRunResult => ({ success: false, skillId, skillVersion, trace: structuredClone(observed), error })
  if (signal.aborted) return Promise.resolve(failure('技能执行已取消'))
  return new Promise(resolve => {
    // No inherited provider keys, NODE_OPTIONS, shell startup or application profile.
    const env: NodeJS.ProcessEnv = {}
    for (const key of ['SystemRoot', 'WINDIR', 'TEMP', 'TMP']) if (process.env[key]) env[key] = process.env[key]
    if (process.versions.electron) env.ELECTRON_RUN_AS_NODE = '1'
    const compiled = fileURLToPath(new URL('./skill-worker.js', import.meta.url))
    // Source-level tests use the worker generated by the mandatory build step.
    const entry = existsSync(compiled) ? compiled : fileURLToPath(new URL('../../../dist/runtime/skills/skill-worker.js', import.meta.url))
    const worker = spawn(process.execPath, ['--max-old-space-size=96', entry], {
      cwd: tmpdir(), env, stdio: ['ignore', 'ignore', 'ignore', 'ipc'], windowsHide: true,
    })
    let outcome: SkillRunResult | undefined
    let calls = 0
    let active = false
    let stopped = false
    const requestIds = new Set<number>()
    const brokerController = new AbortController()
    const combined = AbortSignal.any([signal, brokerController.signal])
    const stop = (message: string): void => {
      if (stopped) return
      stopped = true
      outcome = failure(message)
      brokerController.abort(new Error(message))
      worker.kill()
    }
    const abort = (): void => stop('技能执行已取消')
    signal.addEventListener('abort', abort, { once: true })
    const timer = setTimeout(() => stop('技能执行进程超时，已停止'), 100_000)
    worker.once('error', error => { outcome = failure(error.message) })
    worker.once('close', () => {
      clearTimeout(timer)
      signal.removeEventListener('abort', abort)
      brokerController.abort(new Error('技能执行进程已退出'))
      resolve(outcome ?? failure('技能执行进程异常退出'))
    })
    worker.on('message', async (raw: unknown) => {
      if (stopped || !raw || typeof raw !== 'object') return
      const message = raw as Record<string, any>
      if (message.type === 'result') {
        if (active || !message.result || !Array.isArray(message.result.trace)) { stop('技能进程返回无效结果'); return }
        outcome = message.result as SkillRunResult
        return
      }
      if (message.type !== 'atom' || active || !Number.isSafeInteger(message.id) || requestIds.has(message.id)
        || typeof message.atom !== 'string' || !atoms.has(message.atom) || ++calls > 60
        || !message.args || typeof message.args !== 'object' || Array.isArray(message.args)
        || JSON.stringify(message.args).length > 64_000) { stop('技能进程原子请求越权或超限'); return }
      requestIds.add(message.id)
      active = true
      const receipt: SkillStepTrace = { index: observed.length, atom: message.atom, arguments: structuredClone(message.args), success: false, error: '原子请求尚未完成' }
      observed.push(receipt)
      let response: Record<string, unknown>
      try {
        combined.throwIfAborted()
        const result = await executor(message.atom, message.args, combined)
        combined.throwIfAborted()
        if (JSON.stringify(result ?? null).length > 256_000) throw new Error('原子返回值过大')
        receipt.success = true; receipt.result = result; delete receipt.error
        response = { type: 'atom-result', id: message.id, result: result ?? null }
      } catch (error) {
        const text = error instanceof Error ? error.message : String(error)
        receipt.error = text
        response = { type: 'atom-result', id: message.id, error: text }
      } finally { active = false }
      if (!stopped && worker.connected) worker.send(response, error => { if (error) stop('技能进程通信中断') })
    })
    worker.send({ type: 'run', skillId, skillVersion, program, params, atoms: [...atoms], dependencies: [...dependencies] },
      error => { if (error) stop('技能进程启动通信失败') })
    if (signal.aborted) abort()
  })
}
