import { readFileSync } from 'node:fs'
import { once } from 'node:events'
import WebSocket from 'ws'
import { describe, expect, it, vi } from 'vitest'
import { GameGateway } from '../src/gateway/game-gateway.js'
import { normalizeGameContext, renderGameContextForPrompt } from '../src/runtime/context/game-context.js'
import { registerSwordFormationTools } from '../src/tools/sword-formation-tools.js'
import { PROJECTILE_ATOMS } from '../src/runtime/tasks/sword-formation.js'
import { projectileStateForPrompt, projectileStopMessage } from '../src/runtime/context/projectile-live-state.js'

// Generated by the actual C# controller + GameObservationBuilder + renderer fixture.
// No hand-written "completed" game result; keep RED/GREEN tied to the native evidence.
const native = process.env.AGH_PROJECTILE_STATE_FIXTURE
  ? JSON.parse(readFileSync(process.env.AGH_PROJECTILE_STATE_FIXTURE, 'utf8')) : undefined
const at = native ? Date.parse(native.state.capturedAt) : NaN
const adapter = { gameId: 'stardew-valley', adapterId: 'test', protocolVersion: '1.1', version: 'test' }
const observation = native ? { ...native.observation, meta: { ...native.observation.meta, capturedAt: native.state.capturedAt } } : undefined

describe.skipIf(!native)('native state -> actual context/RPC/voice plumbing (AGH_PROJECTILE_STATE_FIXTURE)', () => {
  it('does not invent readiness on an expired deadline, missing timestamp or inconsistent stop', () => {
    expect(projectileStateForPrompt({ ...native.state, cooldownUntil: new Date(at+100).toISOString() }, at+101)).toMatchObject({ fresh:false })
    expect(projectileStateForPrompt({ ...native.state, capturedAt: undefined }, at)).toMatchObject({ fresh:false })
    expect(projectileStopMessage(native.receipt, 'fallback', at+3100)).toContain('待刷新')
    expect(projectileStopMessage({ ...native.receipt, live:{ ...native.state, active:true } }, 'fallback', at)).toContain('不一致')
  })
  it('keeps the exact native screen label in the current prompt', () => {
    const json = renderGameContextForPrompt(normalizeGameContext(observation, adapter).value, adapter, new Date(at))!
    expect(JSON.parse(json).companion.projectiles.screenLabel).toBe(native.hud[0])
  })
  it.each([1600, 2883, 3100])('does not feed old screen/cooldown claims back after %i ms', age => {
    const json = renderGameContextForPrompt(observation, adapter, new Date(at + age))!
    expect(JSON.parse(json).companion.projectiles).toMatchObject({ fresh: false })
    expect(json).not.toContain(native.state.screenLabel)
    expect(JSON.parse(json).companion.projectiles.active).toBeUndefined()
  })
  it('does not promote a recent outer observation around an old nested state', () => {
    const refreshed = { ...observation, meta: { ...observation.meta, capturedAt: new Date(at+8000).toISOString() } }
    expect(JSON.parse(renderGameContextForPrompt(refreshed, adapter, new Date(at+8000))!).companion.projectiles).toMatchObject({ fresh: false })
  })
  it.each(['dont-starve-together', 'oxygen-not-included'])('adds no sword state for %s', gameId => {
    const input = { schema: 'ai-native.game-context.v1', meta: { gameId, capturedAt: new Date(at).toISOString() }, companion: { present: true } }
    expect(JSON.parse(renderGameContextForPrompt(input, { ...adapter, gameId }, new Date(at))!).companion.projectiles).toBeUndefined()
  })
  it('registered stop tool returns actual native state text', async () => {
    const registered = new Map<string, any>()
    registerSwordFormationTools({ tools: { register: (tool: any) => registered.set(tool.name, tool) } } as never,
      'stardew-valley', new Set(PROJECTILE_ATOMS), async () => native.receipt)
    const clock = vi.spyOn(Date, 'now').mockReturnValue(at)
    try {
      const result = await registered.get('xiaotangyuan_sword_formation_stop').execute({}, { signal: new AbortController().signal })
      expect(result.message).toContain(native.hud[0])
    } finally { clock.mockRestore() }
  })
  it('real Gateway dispatch and voice output keep the native HUD label, no model call for emergency stop', async () => {
    // Real connection, hello, GameAgentSession, dispatch, atom request/reply and notification.
    // External model throws if called; external game replies with the native fixture above.
    const ctx = { logger: { warn: vi.fn() }, agents: { create: () => { throw new Error('emergency stop invoked the model') } } }
    const finishSpeech = vi.fn(async (_pid: number, _id: string, _text: string) => false)
    const gateway = new GameGateway(ctx as never, '127.0.0.1', 0, {} as never, undefined, undefined, {} as never,
      { enabled: false, intervalSeconds: 180 }, () => {}, false, async () => {}, async () => {}, finishSpeech)
    const clock = vi.spyOn(Date, 'now').mockReturnValue(at)
    let socket: WebSocket | undefined
    try {
      await gateway.start([])
      const port = (gateway as any).server.address().port
      socket = new WebSocket(`ws://127.0.0.1:${port}`)
      const notifications: any[] = [], pending = new Map<string, (value: any) => void>()
      let atomCalls = 0
      socket.on('message', data => {
        const message = JSON.parse(data.toString())
        if (message.method === 'game.atom.execute') {
          atomCalls++
          expect(message.params.atom).toBe('stardew.projectiles_cancel')
          socket!.send(JSON.stringify({ jsonrpc: '2.0', id: message.id, result: native.receipt }))
        } else if (message.id && pending.has(message.id)) { pending.get(message.id)!(message); pending.delete(message.id) }
        else notifications.push(message)
      })
      await once(socket, 'open')
      let seq=0
      const request = (method: string, params: object) => new Promise<any>((resolve,reject) => {
        const id = `test-${++seq}`, timer=setTimeout(() => reject(new Error(`timeout: ${method}`)),3000)
        pending.set(id, value => { clearTimeout(timer); value.error ? reject(new Error(value.error.message)) : resolve(value.result) })
        socket!.send(JSON.stringify({ jsonrpc:'2.0', id, method, params }))
      })
      await request('adapter.hello', { ...adapter, processId: 12345, capabilities: ['assistant.text-stream'],
        atoms: [{ name:'stardew.projectiles_cancel', description:'cancel', parameters:'{}', returns:'{}' }] })
      const result = await request('chat.send', { text:'收回剑阵' })
      expect(result.reply).toContain(native.hud[0])
      const voice = await gateway.respond(12345, '收回剑阵', new AbortController().signal)
      expect(voice.reply).toContain(native.hud[0])
      expect(finishSpeech).toHaveBeenCalledWith(12345, expect.any(String), voice.reply)
      expect(atomCalls).toBe(2)
      // Flush a real round-trip so all caption notifications have arrived.
      await request('gateway.ping', {})
      expect(notifications.some(n => n.method === 'assistant.present' && n.params.text === voice.reply)).toBe(true)
    } finally { socket?.terminate(); await gateway.close(); clock.mockRestore() }
  }, 10000)
})
